changelog:
  categories:
    - title: Enhancements
      label: 
        - enhancement
    - title: Bug Fiexes
      label: 
        - bug
        - fixes
  exclude:
    labels:
      - documentation
    authors:
      - dependabot